name: elamlymarket
description: A new Flutter project.

publish_to: 'none'  

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
 


  cupertino_icons: ^1.0.2
  firebase_auth:  
  dio:
  firebase_core: 
  firebase_messaging:  
  permission_handler:
  flutter_local_notifications:
  cloud_firestore:  
  fancy_shimmer_image:
  card_swiper:
  equatable: ^2.0.5
  emailjs:
  pinput:
  flutter_secure_storage:
  flutter:
    sdk: flutter
  flutter_bloc:

  get_it: ^7.6.0 
  flutter_localizations:
   sdk: flutter
  flutter_screenutil: ^5.9.1
  shared_preferences: ^2.2.3
  fluttertoast: ^8.2.5
  open_street_map_search_and_pick: ^0.1.0
  lottie: ^2.7.0
    
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0



flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

 
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy/Gilroy-Medium.ttf
        - asset: assets/fonts/Gilroy/Gilroy-Bold.ttf